version: '2.0'
services:
    weather:
        image: weather
        environment:
            - MONGODB_URI=mongodb://mongodb/weaterDB
        ports:
            - "8080:3000"
        links:
            - mongodb
    mongodb:
        image: mongo